# Generated by Django 3.0.5 on 2020-04-25 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='authro',
            new_name='author',
        ),
    ]
