# Generated by Django 3.0.5 on 2020-04-27 22:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0006_auto_20200428_0043'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postcomment',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterModelOptions(
            name='questioncomment',
            options={'ordering': ['-created_on']},
        ),
        migrations.RenameField(
            model_name='postcomment',
            old_name='comment_text',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='postcomment',
            old_name='comment_date',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='postcomment',
            old_name='by_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='postcomment',
            old_name='comment_by',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='by_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question_by',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='questioncomment',
            old_name='comment_text',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='questioncomment',
            old_name='comment_date',
            new_name='created_on',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='answer_date',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='answer_text',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='answered_by',
        ),
        migrations.RemoveField(
            model_name='postcomment',
            name='comment_for',
        ),
        migrations.RemoveField(
            model_name='question',
            name='answered',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_date',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_text',
        ),
        migrations.RemoveField(
            model_name='questioncomment',
            name='by_email',
        ),
        migrations.RemoveField(
            model_name='questioncomment',
            name='comment_by',
        ),
        migrations.RemoveField(
            model_name='questioncomment',
            name='comment_for',
        ),
        migrations.AddField(
            model_name='answer',
            name='content',
            field=models.TextField(default='Bra bra'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answer',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postcomment',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='postcomment',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.Post'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='content',
            field=models.TextField(default='Bra Bra'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='questioncomment',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='questioncomment',
            name='email',
            field=models.EmailField(default='example@email.com', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questioncomment',
            name='name',
            field=models.CharField(default='Full Name', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questioncomment',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.Question'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='blog.Question'),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
