# Generated by Django 3.0.5 on 2020-04-27 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200428_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomment',
            name='created_on',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
