# Generated by Django 3.0.5 on 2020-04-28 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20200428_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.IntegerField(choices=[(0, 'Not Answered'), (1, 'Answered')], default=0),
        ),
    ]
