# Generated by Django 3.0.5 on 2020-04-28 19:08

from django.db import migrations
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_remove_answer_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='content',
            field=django_summernote.fields.SummernoteTextField(default='Some Text'),
            preserve_default=False,
        ),
    ]
